trigger:
- master

pool:
  name: 'default'

steps:
- task: KubectlInstaller@0
  inputs:
               kubectlVersion: 'latest'
       
- task: AzureCLI@2
  displayName: 'Mount storage and disk'
  inputs:
              azureSubscription: Visual Studio Professional Subscription(5c818070-e938-4382-858f-8d3124e62624)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az aks get-credentials --resource-group gov-devops --name akspriv1
               
                kubectl apply -f dep.yml
                
