trigger:
- master

pool:
  name: 'default'

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'mygovacr20991'
    azureResourceGroup: 'gov-devops'
    kubernetesCluster: 'akspriv1'
    command: 'apply'
    arguments: '-f dep.yml'